from state import PRReviewState

def summarize_pr_node(state: PRReviewState) -> PRReviewState:
    """
    Node 3: summarize_pr
    Takes findings list and PR metadata, generates a PR-comment-style markdown report.
    """
    pr_title = state.get("pr_title", "Pull Request")
    owner = state.get("owner", "")
    repo = state.get("repo", "")
    pr_number = state.get("pr_number", "")
    files = state.get("files", [])
    findings = state.get("findings", [])
    error = state.get("error")

    print(f"📝 [summarize_pr] Generating PR review summary for {len(findings)} findings...")

    if error:
        summary = f"""# 🤖 PR Security & Quality Review

> [!CAUTION]
> **Error Encountered During Review**
> {error}
"""
        return {**state, "summary": summary}

    # Count by severity
    high_count = sum(1 for f in findings if f.get("severity") == "HIGH")
    med_count = sum(1 for f in findings if f.get("severity") == "MEDIUM")
    low_count = sum(1 for f in findings if f.get("severity") == "LOW")

    # Status Banner
    if len(findings) == 0:
        status_banner = "### ✅ Review Status: APPROVED / NO ISSUES FOUND\nNo security vulnerabilities, hardcoded secrets, SQL injection patterns, or missing error handlers were detected in this diff."
    elif high_count > 0:
        status_banner = f"### 🔴 Review Status: ACTION REQUIRED ({high_count} High Severity Issue{'s' if high_count > 1 else ''})\nCritical security vulnerabilities or code defects were detected. Please review before merging."
    else:
        status_banner = f"### 🟡 Review Status: COMMENT / SUGGESTIONS ({len(findings)} Issue{'s' if len(findings) > 1 else ''})\nMinor security or quality improvements identified."

    # Findings Table / Cards
    findings_md = ""
    if findings:
        findings_md += "## 🔍 Detailed Findings & Recommendations\n\n"
        findings_md += "| Severity | Category | File & Line | Issue Description & Suggestion |\n"
        findings_md += "| :---: | :--- | :--- | :--- |\n"
        
        category_labels = {
            "hardcoded_secret": "🔐 Secret Leak",
            "missing_input_validation": "🛡️ Input Validation",
            "sql_injection": "💉 SQL Injection",
            "missing_error_handling": "⚠️ Exception Safety"
        }
        
        severity_badges = {
            "HIGH": "🔴 `HIGH`",
            "MEDIUM": "🟡 `MEDIUM`",
            "LOW": "🔵 `LOW`"
        }
        
        for idx, f in enumerate(findings, 1):
            sev_badge = severity_badges.get(f.get("severity", "MEDIUM"), "`MEDIUM`")
            cat_label = category_labels.get(f.get("category", ""), f.get("category", "General"))
            file_line = f"`{f.get('file', 'N/A')}:{f.get('line', '')}`"
            desc = f.get("description", "").replace("\n", " ")
            sug = f.get("suggestion", "").replace("\n", " ")
            detail = f"**{desc}**<br>💡 *Fix:* {sug}"
            
            findings_md += f"| {sev_badge} | {cat_label} | {file_line} | {detail} |\n"
    else:
        findings_md = "\n*No findings to display. All checks passed successfully!*\n"

    # Category Checklist Summary
    checklist_md = f"""
## 🛡️ Audit Checklist
- [x] **Hardcoded Secrets**: {'❌ Found' if any(f.get('category') == 'hardcoded_secret' for f in findings) else '✅ Clear'}
- [x] **Input Validation**: {'❌ Found' if any(f.get('category') == 'missing_input_validation' for f in findings) else '✅ Clear'}
- [x] **SQL Injection**: {'❌ Found' if any(f.get('category') == 'sql_injection' for f in findings) else '✅ Clear'}
- [x] **Error Handling**: {'❌ Found' if any(f.get('category') == 'missing_error_handling' for f in findings) else '✅ Clear'}
"""

    summary_doc = f"""# 🤖 Automated PR Security & Quality Review

**Repository:** `{owner}/{repo}` | **PR:** #{pr_number} - *"{pr_title}"*  
**Files Changed:** {len(files)} files | **Total Findings:** {len(findings)} ({high_count} High, {med_count} Medium, {low_count} Low)

---

{status_banner}

{checklist_md}

---

{findings_md}

---
*Generated by **LangGraph PR Reviewer Agent Crew*** 🚀
"""
    return {
        **state,
        "summary": summary_doc
    }
